fix fallback to `pk` for `treenode_display_field`
fabiocaccamo/django-treenode pull request #49
Opened 2021-11-16 11:46 UTC by jvacek

2021-11-16 11:47 UTC, jvacek commented
I'm not sure why this test would fail, do you think you could help me with this one @fabiocaccamo?
```
======================================================================
FAIL: test_update_on_delete (tests.test_models.TreeNodeModelsPkTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvacek/Git/django-treenode/tests/test_models.py", line 1155, in test_update_on_delete
    self.assertEqual(a.tn_children_pks, join_pks([ab.pk, ac.pk, ad.pk, ae.pk, af.pk]))
AssertionError: '1001,1002,1003,994,995' != '994,995,1001,1002,1003'
- 1001,1002,1003,994,995
+ 994,995,1001,1002,1003


----------------------------------------------------------------------
Ran 240 tests in 27.703s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

2021-11-16 13:21 UTC, fabiocaccamo commented
@jvacek because the results are sorted alphabetically by their string representation.

2021-12-07 13:11 UTC, fabiocaccamo requested changes

2021-12-07 13:11 UTC, fabiocaccamo commented on treenode/models.py
>              text = f'{self}'
f-string usage breaks tests on python 2.7

2021-12-07 14:00 UTC, merged